# Set this to secure the tokens in the links back to the 
# web server. 
TokenSecret = "set this to secure web requests against spoofing"

# this is used to generate the link back to the reaper's http
# service. Do not add a trailing slash, just include 
# <scheme>://<host:port>
HTTPApiURL = "http://localhost:9000"

# this is where the web server will listen for requests
HTTPListen = "localhost:9000"

[AWS]
# leave these blank to auto-detect / extra information from either 
# an IAM role or environment variables
AccessID     = ""
AccessSecret = ""

# what regions the reaper will look for ec2 servers in
Regions      = [
    "us-west-1",
    "us-west-2",
    "us-east-1",
    "eu-west-1",
]

[SMTP]
Host = "localhost"

# valid: "none", "md5" or "plain". Use "plain" for SES SMTP
AuthType = "none"

# Optional port, defaults to 587
#Port = 587
#Username = ""
#Password = ""

# must be parsable by http://godoc.org/net/mail#ParseAddress
From = "AWS Reaper <reaper@none.mozilla.com>"

[Reaper]
# The time format must be a duration parsable by go's time.ParseDuration 
# function. See: http://godoc.org/time#ParseDuration
# 
# Recommended to do things in hourly increments

# Interval that all instances should be checked for reaping
Interval = "1h"

# How long the instance is allowed to run before sending the first 
# notification
FirstNotification = "12h"

# How long after the first notification before sending the second 
# notification
SecondNotification = "24h"

# How long after the second notification before terminating the instance
Terminate = "24h"


